name: "Custom Env Var"

on: 
  workflow_dispatch:

env:
  DAY_OF_WEEK: Friday
  testvar: value-1

jobs:
  mainjob:
    name: "Print the env vars"
    runs-on: ubuntu-latest
    env:
      Greeting: Dear
    steps:
      - name: "Print the env vars"
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          echo "testvar  $testvar"
          echo "testvar  ${env.testvar}"
        env: 
          First_Name: "Student"
          testvar: value-3
