name: "Custom Env Var"

on: 
  workflow_dispatch:

jobs:
  mainjob:
    name: "Print the env vars"
    runs-on: ubuntu-latest
    env:
      Greeting: Dear
      testvar: value-2
      First_Name: "Student"
      DAY_OF_WEEK: Friday
    steps:
      - name: "Print the env vars"
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          echo "testvar  $testvar"
          echo "testvar  ${env.testvar}"
